export const dataCourse = [
  {
    title: 'JavaScript',
    des: 'Advanced web applications.',
    time: '- 3 h 15 min',
    src: '/imgs/course1.jpg',
  },
  {
    title: 'PowerPoint',
    des: 'Enhance your presentation skills.',
    time: '- 5 h 30 min',
    src: '/imgs/course2.jpg',
  },
  {
    title: 'Data Science',
    des: 'Analyze the data like a pro.',
    time: '- 12 h 25 min',
    src: '/imgs/course3.jpg',
  },
  {
    title: 'Digital Design',
    des: 'Learn the basics of the design.',
    time: '- 2 h 45 min',
    src: '/imgs/course4.jpg',
  },
  {
    title: 'Objective-C',
    des: 'Mobile application development.',
    time: '- 2 h 45 min',
    src: '/imgs/course5.jpg',
  },
  {
    title: 'Python',
    des: 'Enhanced data analysis.',
    time: '- 9 h 05 min',
    src: '/imgs/course6.jpg',
  },
  {
    title: 'Java',
    des: 'Cross-platfrom applications.',
    time: '- 16 h 30 min',
    src: '/imgs/course7.jpg',
  },
  {
    title: 'PHP',
    des: 'Server-side programming.',
    time: '- 5 h 30 min',
    src: '/imgs/course8.jpg',
  },
  {
    title: 'Golang',
    des: 'Backend web development.',
    time: '- 2 h 45 min',
    src: '/imgs/course1.jpg',
  },
  {
    title: 'SwiftUI',
    des: 'Fast prototyping for designers.',
    time: '- 10 h 05 min',
    src: '/imgs/course2.jpg',
  },
  {
    title: 'Github',
    des: 'All that you need to know about it.',
    time: '- 2 h 10 min',
    src: '/imgs/course3.jpg',
  },
  {
    title: 'Research',
    des: 'Learn how to research like a pro.',
    time: '- 9 h 25 min',
    src: '/imgs/course4.jpg',
  },
  {
    title: 'Web Design',
    des: 'Design your first website today.',
    time: '- 4 h 30 min',
    src: '/imgs/course5.jpg',
  },
];
